# Generated by Django 6.0.2 on 2026-05-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('steam_id', models.CharField(blank=True, max_length=50, null=True)),
                ('odehrany_cas', models.IntegerField(default=0)),
                ('stav', models.CharField(choices=[('nedohrano', 'Nedohráno'), ('dohrano', 'Dohráno'), ('nehrat', 'Nebudu hrát')], default='nedohrano', max_length=20)),
                ('priorita', models.CharField(choices=[('vysoka', '🔥 Vysoká'), ('stredni', '⏳ Střední'), ('nizka', '💤 Nízká')], default='stredni', max_length=10)),
                ('achievementy_odemceno', models.IntegerField(default=0)),
                ('achievementy_celkem', models.IntegerField(default=0)),
                ('hodnoceni', models.IntegerField(default=0)),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('hltb_cas', models.IntegerField(default=0)),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
